apiVersion: v1
kind: Pod
metadata:
  name: node-affinity-pod
spec:
  containers:
    - image: data-processor
      name: data-processor
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoreDuringExecution:
        - preference:
            matchExpressions:
              - key: "size"
                operator: "In"
                values: ["Large","Huge"]