apiVersion: v1
kind: LimitRange
metadata: 
   name: cup-limit-range
   namespace: default-mem-namespace
spec:
  limits:
    - default:
        cpu: 1
      defaultRequest:
        cpu: 0.5
      type: Container