apiVersion: v1
kind: Deployment
metadata:
  name: nginx-ingress-controller
spec: 
  replicas: 1
  selector:
    matchLabels:
      name: nginx-ingress
  template:
    metadata: 
      labels: 
        name: nginx-ingress
    spec: 
      containers: 
        - image: quay.io/kubernetes-ingresscontroller/nginx-ingquay.io/kubernetes-ingresscontroller/nginx-ing
          name: nginx-ingress-controller
          args:
            - nginx-ingress-controller
            - --configmap=$(POD_NAMESPACE)/nginx-configuration
        env: 
          - name: POD_NAME
            valueFrom:
              filedRef:
                fieldPath: metadata.name
            name: POD_NAMESPACE
            valueFrom:
              filedRef: 
                fieldPath: metadata.namespace
        ports: 
          - containerPort: 80
            name: http
          - containerPort: 443
            name: https