apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec: 
  completions: 3
  backoffLimit: 15
  template: 
    spec:
      containers:
        - image: perl 
          name: pi
          command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never