apiVersion: v1
kind: Pod
metadata:
  name: security-pod
spec:
  containers:
    - image: busybox
      name: busybox-container
      securityContext:
        runAsUser: 10000
        capabilities: 
          add: ["MAC_ADMIN"]